// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGeneratedReview = "generated_reviews"

// GeneratedReview mapped from table <generated_reviews>
type GeneratedReview struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	ProductID string    `gorm:"column:product_id" json:"product_id"`
	Rating    string    `gorm:"column:rating" json:"rating"`
	Pros      string    `gorm:"column:pros" json:"pros"`
	Cons      string    `gorm:"column:cons" json:"cons"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	Overview  string    `gorm:"column:overview" json:"overview"`
}

// TableName GeneratedReview's table name
func (*GeneratedReview) TableName() string {
	return TableNameGeneratedReview
}
