// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID          string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name        string    `gorm:"column:name" json:"name"`
	URL         string    `gorm:"column:url" json:"url"`
	ImageURL    string    `gorm:"column:image_url" json:"image_url"`
	Description string    `gorm:"column:description" json:"description"`
	Price       string    `gorm:"column:price" json:"price"`
	Rating      float64   `gorm:"column:rating" json:"rating"`
	Summary     string    `gorm:"column:summary" json:"summary"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	Categories  string    `gorm:"column:categories" json:"categories"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
