// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductCategory = "product_categories"

// ProductCategory mapped from table <product_categories>
type ProductCategory struct {
	ProductID  string `gorm:"column:product_id;primaryKey" json:"product_id"`
	CategoryID string `gorm:"column:category_id;primaryKey" json:"category_id"`
}

// TableName ProductCategory's table name
func (*ProductCategory) TableName() string {
	return TableNameProductCategory
}
