// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReview = "reviews"

// Review mapped from table <reviews>
type Review struct {
	ID        string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	ProductID string    `gorm:"column:product_id" json:"product_id"`
	Reviewer  string    `gorm:"column:reviewer" json:"reviewer"`
	Rating    float64   `gorm:"column:rating" json:"rating"`
	Pros      string    `gorm:"column:pros" json:"pros"`
	Cons      string    `gorm:"column:cons" json:"cons"`
	CreatedAt time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	Comment   string    `gorm:"column:comment" json:"comment"`
}

// TableName Review's table name
func (*Review) TableName() string {
	return TableNameReview
}
